# Loads a driving network from OpenStreetMap (osmnx), computes edge weights as travel time
# (length / maxspeed), and runs the A* shortest-path algorithm (heapq) between 10 random
# node pairs per city. Tracks iterations per run, computes the average, and saves
# graph visualizations to the plots/ folder. Cities: Aosta, Turin.

import argparse
import json
import math
import os
import osmnx as ox
import heapq
from  utils import compute_weights, style_visited_edge, style_active_edge, reset_graph, reconstruct_path, get_global_max_speed, compact_json

NUM_RUNS = 10   # number of random pairs per city

PLACES = {
    "Aosta": "Aosta, Aosta, Italy",
    "Turin": "Turin, Piedmont, Italy",
}

def heuristic_manhattan(G, orig, dest):
    """ Compute Manhattan distance between two nodes based on their x/y coordinates. 
    Values should be in meters for better scale with edge weights.
    h(n) = |x1 - x2| + |y1 - y2| """
    x1, y1 = G.nodes[orig]["x"], G.nodes[orig]["y"]
    x2, y2 = G.nodes[dest]["x"], G.nodes[dest]["y"]
    return abs(x1 - x2) + abs(y1 - y2) #meters

def heuristic_euclidean(G, orig, dest):
    """ Compute Euclidean distance between two nodes based on their x/y coordinates. 
    Values should be in meters for better scale with edge weights.
    h(n) = sqrt((x1-x2)^2 + (y1-y2)^2) """
    x1, y1 = G.nodes[orig]["x"], G.nodes[orig]["y"]
    x2, y2 = G.nodes[dest]["x"], G.nodes[dest]["y"]
    # Use osmnx's built-in function 
    return ox.distance.euclidean(y1, x1, y2, x2) #meters

def heuristic_haversine(G, orig, dest):
    """h(n) = great-circle distance via haversine formula (R = 6371 km). 
    Values should be in degrees (lat/lon) for correct distance calculation."""
    lat1, lon1 = G.nodes[orig]["y"], G.nodes[orig]["x"]
    lat2, lon2 = G.nodes[dest]["y"], G.nodes[dest]["x"]
    # Use osmnx's built-in function for great-circle distance
    return ox.distance.great_circle(lat1, lon1, lat2, lon2) #meters

# (h_name, heuristic_func, use_projected_graph)
# Manhattan and Euclidean are run on the projected graph (metres, heuristic is effective).
# Haversine uses the original graph since great_circle() returns metres regardless.
CONFIGS = [
    ("manhattan",           heuristic_manhattan, True),
    ("euclidean",           heuristic_euclidean, True),
    ("haversine",           heuristic_haversine, False),
]

def astar(G, orig, dest, heuristic, max_speed=1):
    """Run A* algorithm from orig to dest using the provided heuristic function, return number of iterations."""
    reset_graph(G)
    G.nodes[orig]["distance"] = 0
    G.nodes[orig]["size"] = 50
    G.nodes[dest]["size"] = 50
    h_n = heuristic(G, orig, dest) / max_speed  # Normalize heuristic by max speed to better balance with g(n)
    pq = [(h_n, orig)]
    step = 0
    while pq:
        _, node = heapq.heappop(pq)
        if node == dest:
            return step
        if G.nodes[node]["visited"]: continue
        G.nodes[node]["visited"] = True
        for edge in G.out_edges(node):
            style_visited_edge(G, (edge[0], edge[1], 0))
            neighbor = edge[1]
            weight = G.edges[(edge[0], edge[1], 0)]["weight"]
            if G.nodes[neighbor]["distance"] > G.nodes[node]["distance"] + weight:
                G.nodes[neighbor]["distance"] = G.nodes[node]["distance"] + weight
                G.nodes[neighbor]["previous"] = node
                h_n = heuristic(G, neighbor, dest) / max_speed  # Normalize heuristic by max speed
                priority = G.nodes[neighbor]["distance"] + h_n
                heapq.heappush(pq, (priority, neighbor))
                for edge2 in G.out_edges(neighbor):
                    style_active_edge(G, (edge2[0], edge2[1], 0))
        step += 1
    return None # No path found

def main():
    parser = argparse.ArgumentParser(description="Run A* on OSM city graphs.")
    parser.add_argument(
        "-n", "--runs",
        type=int,
        default=NUM_RUNS,
        help=f"Number of random pairs per city (default: {NUM_RUNS})",
    )
    args = parser.parse_args()
    num_runs = args.runs

    os.makedirs("plots", exist_ok=True)
    os.makedirs("results", exist_ok=True)

    results_fp = "results/results.json"
    if not os.path.exists(results_fp):
        print(f"ERROR: {results_fp} not found. Run Dijkstra.py first.")
        return
    with open(results_fp) as f:
        all_results = json.load(f)

    for city_name, place_query in PLACES.items():
        city_abbr = city_name.lower()

        # Load fixed pairs generated by Dijkstra
        pairs_fp = f"results/pairs_{city_abbr}.json"
        if not os.path.exists(pairs_fp):
            print(f"ERROR: {pairs_fp} not found. Run Dijkstra.py first.")
            continue
        with open(pairs_fp) as f:
            pairs = json.load(f)

        print(f"\n{'='*55}")
        print(f"  CITY  : {city_name}")
        print(f"  Query : {place_query}")
        print(f"  Loading graph...")
        G = ox.graph_from_place(place_query, network_type="drive")
        compute_weights(G)  # compute "weight" attribute for each edge based on length and maxspeed
        max_speed = get_global_max_speed(G)
        print(f"  Graph : {len(G.nodes):,} nodes, {len(G.edges):,} edges")
        print(f"  Using {len(pairs)} fixed pairs from Dijkstra run")
        G_original = G.copy()  # keep a copy of the original graph
        G_projected = ox.project_graph(G)  # project to metric for accurate distance calculations
        for h_name, h_func, use_projected in CONFIGS:
            print(f"\n  {'─'*49}")
            print(f"  Heuristic : A* [{h_name} | {'projected' if use_projected else 'original'} graph]")
            print(f"  {'─'*49}")

            G = G_projected if use_projected else G_original

            for edge in G.edges:
                G.edges[edge]["astar_uses"] = 0

            run_results = []
            for i, (start, end) in enumerate(pairs[:num_runs], 1):
                steps = astar(G, start, end, h_func, max_speed=max_speed)
                if steps is None:
                    print(f"    Run {i:2d}/{num_runs} | WARNING: no path found for this pair")
                    run_results.append({"iterations": None, "distance_km": None, "travel_time_s": None})
                    continue
                city_acronym = "A" + city_name[:2].upper() + h_name.upper().replace("_", "")[:6]
                fp = f"plots/astar/{city_abbr}/{h_name}/run{i:02d}_{city_acronym}.png"
                dist, travel_time = reconstruct_path(G, start, end, plot=True, algorithm="astar", filepath=fp)
                run_results.append({"iterations": steps, "distance_km": round(dist, 4), "travel_time_s": round(travel_time, 2)})
                print(f"    Run {i:2d}/{num_runs} | Iterations: {steps:6d} | Distance: {dist:.2f} km | Time: {travel_time:.1f} s | Plot saved: {fp}")

            valid = [r for r in run_results if r["iterations"] is not None]
            avg = sum(r["iterations"] for r in valid) / len(valid) if valid else 0
            print(f"\n    Steps per run       : {[r['iterations'] for r in run_results]}")
            print(f"    Travel times (s)    : {[r['travel_time_s'] for r in run_results]}")
            print(f"    Average steps       : {avg:.1f}")

            # Update results for this city/heuristic
            all_results[city_name]["results"][f"astar_{h_name}"] = {
                "iterations":    [r["iterations"]    for r in run_results],
                "distance_km":   [r["distance_km"]   for r in run_results],
                "travel_time_s": [r["travel_time_s"] for r in run_results],
                "average":       round(avg, 2),
            }

        # Write updated results after each city
        with open(results_fp, "w") as f:
            f.write(compact_json(all_results))

    print(f"\n  Results saved : {results_fp}")


if __name__ == "__main__":
    main()

